//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.25 at 02:42:22 PM PDT 
//


package org.jivesoftware.smackx.sensorread.packet.generatedmodels;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.jivesoftware.smackx.sensorread.packet.AbstractSensorReadResponse;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="node">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="timestamp">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                             &lt;element name="boolean" type="{urn:xmpp:iot:sensordata}boolean"/>
 *                             &lt;element name="date" type="{urn:xmpp:iot:sensordata}date"/>
 *                             &lt;element name="dateTime" type="{urn:xmpp:iot:sensordata}dateTime"/>
 *                             &lt;element name="duration" type="{urn:xmpp:iot:sensordata}duration"/>
 *                             &lt;element name="enum" type="{urn:xmpp:iot:sensordata}enum"/>
 *                             &lt;element name="int" type="{urn:xmpp:iot:sensordata}int"/>
 *                             &lt;element name="long" type="{urn:xmpp:iot:sensordata}long"/>
 *                             &lt;element name="numeric" type="{urn:xmpp:iot:sensordata}numeric"/>
 *                             &lt;element name="string" type="{urn:xmpp:iot:sensordata}string"/>
 *                             &lt;element name="time" type="{urn:xmpp:iot:sensordata}time"/>
 *                           &lt;/choice>
 *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="nodeId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="sourceId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="cacheType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="seqnr" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="done" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "node"
})
@XmlRootElement(name = "fields")
public class Fields extends AbstractSensorReadResponse {

    protected List<Fields.Node> node;
//    @XmlAttribute(name = "seqnr", required = true)
//    protected int seqnr;
    @XmlAttribute(name = "done")
    protected java.lang.Boolean done;

    @XmlAttribute(name = "seqnr", required = true)
    protected int seqnr;
	
	public int getSeqnr() {
		return seqnr;
	}

	public void setSeqnr(int seqnr) {
		this.seqnr = seqnr;
	}
	
    /**
     * Gets the value of the node property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the node property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Fields.Node }
     * 
     * 
     */
    public List<Fields.Node> getNode() {
        if (node == null) {
            node = new ArrayList<Fields.Node>();
        }
        return this.node;
    }

    /**
     * Gets the value of the done property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isDone() {
        if (done == null) {
            return false;
        } else {
            return done;
        }
    }

    /**
     * Sets the value of the done property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setDone(java.lang.Boolean value) {
        this.done = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="timestamp">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
     *                   &lt;element name="boolean" type="{urn:xmpp:iot:sensordata}boolean"/>
     *                   &lt;element name="date" type="{urn:xmpp:iot:sensordata}date"/>
     *                   &lt;element name="dateTime" type="{urn:xmpp:iot:sensordata}dateTime"/>
     *                   &lt;element name="duration" type="{urn:xmpp:iot:sensordata}duration"/>
     *                   &lt;element name="enum" type="{urn:xmpp:iot:sensordata}enum"/>
     *                   &lt;element name="int" type="{urn:xmpp:iot:sensordata}int"/>
     *                   &lt;element name="long" type="{urn:xmpp:iot:sensordata}long"/>
     *                   &lt;element name="numeric" type="{urn:xmpp:iot:sensordata}numeric"/>
     *                   &lt;element name="string" type="{urn:xmpp:iot:sensordata}string"/>
     *                   &lt;element name="time" type="{urn:xmpp:iot:sensordata}time"/>
     *                 &lt;/choice>
     *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="nodeId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="sourceId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="cacheType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "timestamp"
    })
    public static class Node {

        protected List<Fields.Node.Timestamp> timestamp;
        @XmlAttribute(name = "nodeId", required = true)
        protected java.lang.String nodeId;
        @XmlAttribute(name = "sourceId")
        protected java.lang.String sourceId;
        @XmlAttribute(name = "cacheType")
        protected java.lang.String cacheType;

        /**
         * Gets the value of the timestamp property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the timestamp property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTimestamp().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Fields.Node.Timestamp }
         * 
         * 
         */
        public List<Fields.Node.Timestamp> getTimestamp() {
            if (timestamp == null) {
                timestamp = new ArrayList<Fields.Node.Timestamp>();
            }
            return this.timestamp;
        }

        /**
         * Gets the value of the nodeId property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String }
         *     
         */
        public java.lang.String getNodeId() {
            return nodeId;
        }

        /**
         * Sets the value of the nodeId property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String }
         *     
         */
        public void setNodeId(java.lang.String value) {
            this.nodeId = value;
        }

        /**
         * Gets the value of the sourceId property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String }
         *     
         */
        public java.lang.String getSourceId() {
            return sourceId;
        }

        /**
         * Sets the value of the sourceId property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String }
         *     
         */
        public void setSourceId(java.lang.String value) {
            this.sourceId = value;
        }

        /**
         * Gets the value of the cacheType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String }
         *     
         */
        public java.lang.String getCacheType() {
            return cacheType;
        }

        /**
         * Sets the value of the cacheType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String }
         *     
         */
        public void setCacheType(java.lang.String value) {
            this.cacheType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice maxOccurs="unbounded" minOccurs="0">
         *         &lt;element name="boolean" type="{urn:xmpp:iot:sensordata}boolean"/>
         *         &lt;element name="date" type="{urn:xmpp:iot:sensordata}date"/>
         *         &lt;element name="dateTime" type="{urn:xmpp:iot:sensordata}dateTime"/>
         *         &lt;element name="duration" type="{urn:xmpp:iot:sensordata}duration"/>
         *         &lt;element name="enum" type="{urn:xmpp:iot:sensordata}enum"/>
         *         &lt;element name="int" type="{urn:xmpp:iot:sensordata}int"/>
         *         &lt;element name="long" type="{urn:xmpp:iot:sensordata}long"/>
         *         &lt;element name="numeric" type="{urn:xmpp:iot:sensordata}numeric"/>
         *         &lt;element name="string" type="{urn:xmpp:iot:sensordata}string"/>
         *         &lt;element name="time" type="{urn:xmpp:iot:sensordata}time"/>
         *       &lt;/choice>
         *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fields"
        })
        public static class Timestamp {

            @XmlElements({
                @XmlElement(name = "boolean", type = XMPPIoTBoolean.class),
                @XmlElement(name = "date", type = XMPPIoTDate.class),
                @XmlElement(name = "dateTime", type = DateTime.class),
                @XmlElement(name = "duration", type = Duration.class),
                @XmlElement(name = "enum", type = XMPPIoTEnum.class),
                @XmlElement(name = "int", type = XMPPIoTInt.class),
                @XmlElement(name = "long", type = XMPPIoTLong.class),
                @XmlElement(name = "numeric", type = Numeric.class),
                @XmlElement(name = "string", type = XMPPIoTString.class),
                @XmlElement(name = "time", type = XMPPIoTTime.class)
            })
            
//            protected List<XMPPIoTBoolean> booleans = new ArrayList<XMPPIoTBoolean>();
//            protected List<Date> dates = new ArrayList<Date>();
//            protected List<DateTime> datetimes = new ArrayList<DateTime>();
//            protected List<Duration> durations = new ArrayList<Duration>();
//            protected List<Enum> enums = new ArrayList<Enum>();
//            protected List<Int> ints = new ArrayList<Int>();
//            protected List<Long> longs = new ArrayList<Long>();
//            protected List<Numeric> numerics = new ArrayList<Numeric>();
//            protected List<String> strings = new ArrayList<String>();
//            protected List<Time> times = new ArrayList<Time>();
//        	
            protected List<Field> fields;
            @XmlAttribute(name = "value", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar value;

            /**
             * Gets the value of the booleanOrDateOrDateTime property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the booleanOrDateOrDateTime property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBooleanOrDateOrDateTime().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link XMPPIoTBoolean }
             * {@link XMPPIoTDate }
             * {@link DateTime }
             * {@link Duration }
             * {@link XMPPIoTEnum }
             * {@link XMPPIoTInt }
             * {@link XMPPIoTLong }
             * {@link Numeric }
             * {@link XMPPIoTString }
             * {@link XMPPIoTTime }
             * 
             * 
             */
            public List<Field> getFields() {
                if (fields == null) {
                    fields = new ArrayList<Field>();
                }
                return this.fields;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setValue(XMLGregorianCalendar value) {
                this.value = value;
            }

        }

    }

	@Override
	public void seq(int seq) {
		setSeqnr(seq);
	}

}
