//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.25 at 02:42:22 PM PDT 
//


package org.jivesoftware.smackx.sensorread.packet.generatedmodels;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for field complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="field">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{urn:xmpp:iot:sensordata}fieldTypes"/>
 *       &lt;attGroup ref="{urn:xmpp:iot:sensordata}fieldQoS"/>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="module" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="stringIds" type="{urn:xmpp:iot:sensordata}StringIds" />
 *       &lt;attribute name="writable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "field")
@XmlSeeAlso({
    XMPPIoTTime.class,
    Duration.class,
    Numeric.class,
    DateTime.class,
    XMPPIoTInt.class,
    XMPPIoTString.class,
    XMPPIoTEnum.class,
    XMPPIoTBoolean.class,
    XMPPIoTLong.class,
    XMPPIoTDate.class
})
public abstract class Field {

    @XmlAttribute(name = "name", required = true)
    protected java.lang.String name;
    @XmlAttribute(name = "module")
    protected java.lang.String module;
    @XmlAttribute(name = "stringIds")
    protected java.lang.String stringIds;
    @XmlAttribute(name = "writable")
    protected java.lang.Boolean writable;
    @XmlAttribute(name = "momentary")
    protected java.lang.Boolean momentary;
    @XmlAttribute(name = "peak")
    protected java.lang.Boolean peak;
    @XmlAttribute(name = "status")
    protected java.lang.Boolean status;
    @XmlAttribute(name = "computed")
    protected java.lang.Boolean computed;
    @XmlAttribute(name = "identity")
    protected java.lang.Boolean identity;
    @XmlAttribute(name = "historicalSecond")
    protected java.lang.Boolean historicalSecond;
    @XmlAttribute(name = "historicalMinute")
    protected java.lang.Boolean historicalMinute;
    @XmlAttribute(name = "historicalHour")
    protected java.lang.Boolean historicalHour;
    @XmlAttribute(name = "historicalDay")
    protected java.lang.Boolean historicalDay;
    @XmlAttribute(name = "historicalWeek")
    protected java.lang.Boolean historicalWeek;
    @XmlAttribute(name = "historicalMonth")
    protected java.lang.Boolean historicalMonth;
    @XmlAttribute(name = "historicalQuarter")
    protected java.lang.Boolean historicalQuarter;
    @XmlAttribute(name = "historicalYear")
    protected java.lang.Boolean historicalYear;
    @XmlAttribute(name = "historicalOther")
    protected java.lang.Boolean historicalOther;
    @XmlAttribute(name = "missing")
    protected java.lang.Boolean missing;
    @XmlAttribute(name = "inProgress")
    protected java.lang.Boolean inProgress;
    @XmlAttribute(name = "automaticEstimate")
    protected java.lang.Boolean automaticEstimate;
    @XmlAttribute(name = "manualEstimate")
    protected java.lang.Boolean manualEstimate;
    @XmlAttribute(name = "manualReadout")
    protected java.lang.Boolean manualReadout;
    @XmlAttribute(name = "automaticReadout")
    protected java.lang.Boolean automaticReadout;
    @XmlAttribute(name = "timeOffset")
    protected java.lang.Boolean timeOffset;
    @XmlAttribute(name = "warning")
    protected java.lang.Boolean warning;
    @XmlAttribute(name = "error")
    protected java.lang.Boolean error;
    @XmlAttribute(name = "signed")
    protected java.lang.Boolean signed;
    @XmlAttribute(name = "invoiced")
    protected java.lang.Boolean invoiced;
    @XmlAttribute(name = "endOfSeries")
    protected java.lang.Boolean endOfSeries;
    @XmlAttribute(name = "powerFailure")
    protected java.lang.Boolean powerFailure;
    @XmlAttribute(name = "invoiceConfirmed")
    protected java.lang.Boolean invoiceConfirmed;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setName(java.lang.String value) {
        this.name = value;
    }

    /**
     * Gets the value of the module property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getModule() {
        return module;
    }

    /**
     * Sets the value of the module property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setModule(java.lang.String value) {
        this.module = value;
    }

    /**
     * Gets the value of the stringIds property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getStringIds() {
        return stringIds;
    }

    /**
     * Sets the value of the stringIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setStringIds(java.lang.String value) {
        this.stringIds = value;
    }

    /**
     * Gets the value of the writable property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public java.lang.Boolean isWritable() {
        return writable;
    }

    /**
     * Sets the value of the writable property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setWritable(java.lang.Boolean value) {
        this.writable = value;
    }

    /**
     * Gets the value of the momentary property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isMomentary() {
        if (momentary == null) {
            return false;
        } else {
            return momentary;
        }
    }

    /**
     * Sets the value of the momentary property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setMomentary(java.lang.Boolean value) {
        this.momentary = value;
    }

    /**
     * Gets the value of the peak property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isPeak() {
        if (peak == null) {
            return false;
        } else {
            return peak;
        }
    }

    /**
     * Sets the value of the peak property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setPeak(java.lang.Boolean value) {
        this.peak = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isStatus() {
        if (status == null) {
            return false;
        } else {
            return status;
        }
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setStatus(java.lang.Boolean value) {
        this.status = value;
    }

    /**
     * Gets the value of the computed property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isComputed() {
        if (computed == null) {
            return false;
        } else {
            return computed;
        }
    }

    /**
     * Sets the value of the computed property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setComputed(java.lang.Boolean value) {
        this.computed = value;
    }

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isIdentity() {
        if (identity == null) {
            return false;
        } else {
            return identity;
        }
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setIdentity(java.lang.Boolean value) {
        this.identity = value;
    }

    /**
     * Gets the value of the historicalSecond property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalSecond() {
        if (historicalSecond == null) {
            return false;
        } else {
            return historicalSecond;
        }
    }

    /**
     * Sets the value of the historicalSecond property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalSecond(java.lang.Boolean value) {
        this.historicalSecond = value;
    }

    /**
     * Gets the value of the historicalMinute property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalMinute() {
        if (historicalMinute == null) {
            return false;
        } else {
            return historicalMinute;
        }
    }

    /**
     * Sets the value of the historicalMinute property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalMinute(java.lang.Boolean value) {
        this.historicalMinute = value;
    }

    /**
     * Gets the value of the historicalHour property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalHour() {
        if (historicalHour == null) {
            return false;
        } else {
            return historicalHour;
        }
    }

    /**
     * Sets the value of the historicalHour property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalHour(java.lang.Boolean value) {
        this.historicalHour = value;
    }

    /**
     * Gets the value of the historicalDay property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalDay() {
        if (historicalDay == null) {
            return false;
        } else {
            return historicalDay;
        }
    }

    /**
     * Sets the value of the historicalDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalDay(java.lang.Boolean value) {
        this.historicalDay = value;
    }

    /**
     * Gets the value of the historicalWeek property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalWeek() {
        if (historicalWeek == null) {
            return false;
        } else {
            return historicalWeek;
        }
    }

    /**
     * Sets the value of the historicalWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalWeek(java.lang.Boolean value) {
        this.historicalWeek = value;
    }

    /**
     * Gets the value of the historicalMonth property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalMonth() {
        if (historicalMonth == null) {
            return false;
        } else {
            return historicalMonth;
        }
    }

    /**
     * Sets the value of the historicalMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalMonth(java.lang.Boolean value) {
        this.historicalMonth = value;
    }

    /**
     * Gets the value of the historicalQuarter property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalQuarter() {
        if (historicalQuarter == null) {
            return false;
        } else {
            return historicalQuarter;
        }
    }

    /**
     * Sets the value of the historicalQuarter property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalQuarter(java.lang.Boolean value) {
        this.historicalQuarter = value;
    }

    /**
     * Gets the value of the historicalYear property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalYear() {
        if (historicalYear == null) {
            return false;
        } else {
            return historicalYear;
        }
    }

    /**
     * Sets the value of the historicalYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalYear(java.lang.Boolean value) {
        this.historicalYear = value;
    }

    /**
     * Gets the value of the historicalOther property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalOther() {
        if (historicalOther == null) {
            return false;
        } else {
            return historicalOther;
        }
    }

    /**
     * Sets the value of the historicalOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalOther(java.lang.Boolean value) {
        this.historicalOther = value;
    }

    /**
     * Gets the value of the missing property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isMissing() {
        if (missing == null) {
            return false;
        } else {
            return missing;
        }
    }

    /**
     * Sets the value of the missing property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setMissing(java.lang.Boolean value) {
        this.missing = value;
    }

    /**
     * Gets the value of the inProgress property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isInProgress() {
        if (inProgress == null) {
            return false;
        } else {
            return inProgress;
        }
    }

    /**
     * Sets the value of the inProgress property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setInProgress(java.lang.Boolean value) {
        this.inProgress = value;
    }

    /**
     * Gets the value of the automaticEstimate property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isAutomaticEstimate() {
        if (automaticEstimate == null) {
            return false;
        } else {
            return automaticEstimate;
        }
    }

    /**
     * Sets the value of the automaticEstimate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setAutomaticEstimate(java.lang.Boolean value) {
        this.automaticEstimate = value;
    }

    /**
     * Gets the value of the manualEstimate property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isManualEstimate() {
        if (manualEstimate == null) {
            return false;
        } else {
            return manualEstimate;
        }
    }

    /**
     * Sets the value of the manualEstimate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setManualEstimate(java.lang.Boolean value) {
        this.manualEstimate = value;
    }

    /**
     * Gets the value of the manualReadout property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isManualReadout() {
        if (manualReadout == null) {
            return false;
        } else {
            return manualReadout;
        }
    }

    /**
     * Sets the value of the manualReadout property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setManualReadout(java.lang.Boolean value) {
        this.manualReadout = value;
    }

    /**
     * Gets the value of the automaticReadout property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isAutomaticReadout() {
        if (automaticReadout == null) {
            return false;
        } else {
            return automaticReadout;
        }
    }

    /**
     * Sets the value of the automaticReadout property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setAutomaticReadout(java.lang.Boolean value) {
        this.automaticReadout = value;
    }

    /**
     * Gets the value of the timeOffset property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isTimeOffset() {
        if (timeOffset == null) {
            return false;
        } else {
            return timeOffset;
        }
    }

    /**
     * Sets the value of the timeOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setTimeOffset(java.lang.Boolean value) {
        this.timeOffset = value;
    }

    /**
     * Gets the value of the warning property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isWarning() {
        if (warning == null) {
            return false;
        } else {
            return warning;
        }
    }

    /**
     * Sets the value of the warning property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setWarning(java.lang.Boolean value) {
        this.warning = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isError() {
        if (error == null) {
            return false;
        } else {
            return error;
        }
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setError(java.lang.Boolean value) {
        this.error = value;
    }

    /**
     * Gets the value of the signed property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isSigned() {
        if (signed == null) {
            return false;
        } else {
            return signed;
        }
    }

    /**
     * Sets the value of the signed property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setSigned(java.lang.Boolean value) {
        this.signed = value;
    }

    /**
     * Gets the value of the invoiced property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isInvoiced() {
        if (invoiced == null) {
            return false;
        } else {
            return invoiced;
        }
    }

    /**
     * Sets the value of the invoiced property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setInvoiced(java.lang.Boolean value) {
        this.invoiced = value;
    }

    /**
     * Gets the value of the endOfSeries property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isEndOfSeries() {
        if (endOfSeries == null) {
            return false;
        } else {
            return endOfSeries;
        }
    }

    /**
     * Sets the value of the endOfSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setEndOfSeries(java.lang.Boolean value) {
        this.endOfSeries = value;
    }

    /**
     * Gets the value of the powerFailure property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isPowerFailure() {
        if (powerFailure == null) {
            return false;
        } else {
            return powerFailure;
        }
    }

    /**
     * Sets the value of the powerFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setPowerFailure(java.lang.Boolean value) {
        this.powerFailure = value;
    }

    /**
     * Gets the value of the invoiceConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isInvoiceConfirmed() {
        if (invoiceConfirmed == null) {
            return false;
        } else {
            return invoiceConfirmed;
        }
    }

    /**
     * Sets the value of the invoiceConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setInvoiceConfirmed(java.lang.Boolean value) {
        this.invoiceConfirmed = value;
    }

}
