//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.25 at 02:42:22 PM PDT 
//


package org.jivesoftware.smackx.sensorread.packet.generatedmodels;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nhong.xep323.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nhong.xep323.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Failure }
     * 
     */
    public Failure createFailure() {
        return new Failure();
    }

    /**
     * Create an instance of {@link Req }
     * 
     */
    public Req createReq() {
        return new Req();
    }

    /**
     * Create an instance of {@link Fields }
     * 
     */
    public Fields createFields() {
        return new Fields();
    }

    /**
     * Create an instance of {@link Fields.Node }
     * 
     */
    public Fields.Node createFieldsNode() {
        return new Fields.Node();
    }

    /**
     * Create an instance of {@link Failure.Error }
     * 
     */
    public Failure.Error createFailureError() {
        return new Failure.Error();
    }

    /**
     * Create an instance of {@link Accepted }
     * 
     */
    public Accepted createAccepted() {
        return new Accepted();
    }

    /**
     * Create an instance of {@link Done }
     * 
     */
    public Done createDone() {
        return new Done();
    }

    /**
     * Create an instance of {@link Cancelled }
     * 
     */
    public Cancelled createCancelled() {
        return new Cancelled();
    }

    /**
     * Create an instance of {@link Cancel }
     * 
     */
    public Cancel createCancel() {
        return new Cancel();
    }

    /**
     * Create an instance of {@link Started }
     * 
     */
    public Started createStarted() {
        return new Started();
    }

    /**
     * Create an instance of {@link Req.Node }
     * 
     */
    public Req.Node createReqNode() {
        return new Req.Node();
    }

    /**
     * Create an instance of {@link Req.Field }
     * 
     */
    public Req.Field createReqField() {
        return new Req.Field();
    }

    /**
     * Create an instance of {@link XMPPIoTTime }
     * 
     */
    public XMPPIoTTime createTime() {
        return new XMPPIoTTime();
    }

    /**
     * Create an instance of {@link Duration }
     * 
     */
    public Duration createDuration() {
        return new Duration();
    }

    /**
     * Create an instance of {@link Numeric }
     * 
     */
    public Numeric createNumeric() {
        return new Numeric();
    }

    /**
     * Create an instance of {@link DateTime }
     * 
     */
    public DateTime createDateTime() {
        return new DateTime();
    }

    /**
     * Create an instance of {@link XMPPIoTInt }
     * 
     */
    public XMPPIoTInt createInt() {
        return new XMPPIoTInt();
    }

    /**
     * Create an instance of {@link XMPPIoTString }
     * 
     */
    public XMPPIoTString createString() {
        return new XMPPIoTString();
    }

    /**
     * Create an instance of {@link XMPPIoTEnum }
     * 
     */
    public XMPPIoTEnum createEnum() {
        return new XMPPIoTEnum();
    }

    /**
     * Create an instance of {@link XMPPIoTBoolean }
     * 
     */
    public XMPPIoTBoolean createBoolean() {
        return new XMPPIoTBoolean();
    }

    /**
     * Create an instance of {@link XMPPIoTLong }
     * 
     */
    public XMPPIoTLong createLong() {
        return new XMPPIoTLong();
    }

    /**
     * Create an instance of {@link XMPPIoTDate }
     * 
     */
    public XMPPIoTDate createDate() {
        return new XMPPIoTDate();
    }

    /**
     * Create an instance of {@link Fields.Node.Timestamp }
     * 
     */
    public Fields.Node.Timestamp createFieldsNodeTimestamp() {
        return new Fields.Node.Timestamp();
    }

}
