//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.25 at 02:42:22 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:xmpp:iot:sensordata", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.jivesoftware.smackx.sensorread.packet.generatedmodels;
