//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.25 at 02:42:22 PM PDT 
//


package org.jivesoftware.smackx.sensorread.packet.generatedmodels;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="node">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="nodeId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="sourceId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="cacheType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="field">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attGroup ref="{urn:xmpp:iot:sensordata}fieldTypes"/>
 *       &lt;attribute name="seqnr" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="all" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="historical" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="to" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="when" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="serviceToken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="deviceToken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="userToken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nodeOrField"
})
@XmlRootElement(name = "req")
public class Req {
 
    @XmlElements({
        @XmlElement(name = "node", type = Req.Node.class),
        @XmlElement(name = "field", type = Req.Field.class)
    })
    protected List<Object> nodeOrField;
    @XmlAttribute(name = "seqnr", required = true)
    protected int seqnr;
    @XmlAttribute(name = "all")
    protected java.lang.Boolean all;
    @XmlAttribute(name = "historical")
    protected java.lang.Boolean historical;
    @XmlAttribute(name = "from")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar from;
    @XmlAttribute(name = "to")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar to;
    @XmlAttribute(name = "when")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar when;
    @XmlAttribute(name = "serviceToken")
    protected java.lang.String serviceToken;
    @XmlAttribute(name = "deviceToken")
    protected java.lang.String deviceToken;
    @XmlAttribute(name = "userToken")
    protected java.lang.String userToken;
    @XmlAttribute(name = "momentary")
    protected java.lang.Boolean momentary;
    @XmlAttribute(name = "peak")
    protected java.lang.Boolean peak;
    @XmlAttribute(name = "status")
    protected java.lang.Boolean status;
    @XmlAttribute(name = "computed")
    protected java.lang.Boolean computed;
    @XmlAttribute(name = "identity")
    protected java.lang.Boolean identity;
    @XmlAttribute(name = "historicalSecond")
    protected java.lang.Boolean historicalSecond;
    @XmlAttribute(name = "historicalMinute")
    protected java.lang.Boolean historicalMinute;
    @XmlAttribute(name = "historicalHour")
    protected java.lang.Boolean historicalHour;
    @XmlAttribute(name = "historicalDay")
    protected java.lang.Boolean historicalDay;
    @XmlAttribute(name = "historicalWeek")
    protected java.lang.Boolean historicalWeek;
    @XmlAttribute(name = "historicalMonth")
    protected java.lang.Boolean historicalMonth;
    @XmlAttribute(name = "historicalQuarter")
    protected java.lang.Boolean historicalQuarter;
    @XmlAttribute(name = "historicalYear")
    protected java.lang.Boolean historicalYear;
    @XmlAttribute(name = "historicalOther")
    protected java.lang.Boolean historicalOther;

    /**
     * Gets the value of the nodeOrField property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nodeOrField property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNodeOrField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Req.Node }
     * {@link Req.Field }
     * 
     * 
     */
    public List<Object> getNodeOrField() {
        if (nodeOrField == null) {
            nodeOrField = new ArrayList<Object>();
        }
        return this.nodeOrField;
    }

    /**
     * Gets the value of the seqnr property.
     * 
     */
    public int getSeqnr() {
        return seqnr;
    }

    /**
     * Sets the value of the seqnr property.
     * 
     */
    public void setSeqnr(int value) {
        this.seqnr = value;
    }

    /**
     * Gets the value of the all property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isAll() {
        if (all == null) {
            return false;
        } else {
            return all;
        }
    }

    /**
     * Sets the value of the all property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setAll(java.lang.Boolean value) {
        this.all = value;
    }

    /**
     * Gets the value of the historical property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistorical() {
        if (historical == null) {
            return false;
        } else {
            return historical;
        }
    }

    /**
     * Sets the value of the historical property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistorical(java.lang.Boolean value) {
        this.historical = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFrom(XMLGregorianCalendar value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTo(XMLGregorianCalendar value) {
        this.to = value;
    }

    /**
     * Gets the value of the when property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWhen() {
        return when;
    }

    /**
     * Sets the value of the when property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWhen(XMLGregorianCalendar value) {
        this.when = value;
    }

    /**
     * Gets the value of the serviceToken property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getServiceToken() {
        return serviceToken;
    }

    /**
     * Sets the value of the serviceToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setServiceToken(java.lang.String value) {
        this.serviceToken = value;
    }

    /**
     * Gets the value of the deviceToken property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDeviceToken() {
        return deviceToken;
    }

    /**
     * Sets the value of the deviceToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDeviceToken(java.lang.String value) {
        this.deviceToken = value;
    }

    /**
     * Gets the value of the userToken property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getUserToken() {
        return userToken;
    }

    /**
     * Sets the value of the userToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setUserToken(java.lang.String value) {
        this.userToken = value;
    }

    /**
     * Gets the value of the momentary property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isMomentary() {
        if (momentary == null) {
            return false;
        } else {
            return momentary;
        }
    }

    /**
     * Sets the value of the momentary property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setMomentary(java.lang.Boolean value) {
        this.momentary = value;
    }

    /**
     * Gets the value of the peak property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isPeak() {
        if (peak == null) {
            return false;
        } else {
            return peak;
        }
    }

    /**
     * Sets the value of the peak property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setPeak(java.lang.Boolean value) {
        this.peak = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isStatus() {
        if (status == null) {
            return false;
        } else {
            return status;
        }
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setStatus(java.lang.Boolean value) {
        this.status = value;
    }

    /**
     * Gets the value of the computed property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isComputed() {
        if (computed == null) {
            return false;
        } else {
            return computed;
        }
    }

    /**
     * Sets the value of the computed property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setComputed(java.lang.Boolean value) {
        this.computed = value;
    }

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isIdentity() {
        if (identity == null) {
            return false;
        } else {
            return identity;
        }
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setIdentity(java.lang.Boolean value) {
        this.identity = value;
    }

    /**
     * Gets the value of the historicalSecond property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalSecond() {
        if (historicalSecond == null) {
            return false;
        } else {
            return historicalSecond;
        }
    }

    /**
     * Sets the value of the historicalSecond property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalSecond(java.lang.Boolean value) {
        this.historicalSecond = value;
    }

    /**
     * Gets the value of the historicalMinute property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalMinute() {
        if (historicalMinute == null) {
            return false;
        } else {
            return historicalMinute;
        }
    }

    /**
     * Sets the value of the historicalMinute property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalMinute(java.lang.Boolean value) {
        this.historicalMinute = value;
    }

    /**
     * Gets the value of the historicalHour property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalHour() {
        if (historicalHour == null) {
            return false;
        } else {
            return historicalHour;
        }
    }

    /**
     * Sets the value of the historicalHour property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalHour(java.lang.Boolean value) {
        this.historicalHour = value;
    }

    /**
     * Gets the value of the historicalDay property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalDay() {
        if (historicalDay == null) {
            return false;
        } else {
            return historicalDay;
        }
    }

    /**
     * Sets the value of the historicalDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalDay(java.lang.Boolean value) {
        this.historicalDay = value;
    }

    /**
     * Gets the value of the historicalWeek property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalWeek() {
        if (historicalWeek == null) {
            return false;
        } else {
            return historicalWeek;
        }
    }

    /**
     * Sets the value of the historicalWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalWeek(java.lang.Boolean value) {
        this.historicalWeek = value;
    }

    /**
     * Gets the value of the historicalMonth property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalMonth() {
        if (historicalMonth == null) {
            return false;
        } else {
            return historicalMonth;
        }
    }

    /**
     * Sets the value of the historicalMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalMonth(java.lang.Boolean value) {
        this.historicalMonth = value;
    }

    /**
     * Gets the value of the historicalQuarter property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalQuarter() {
        if (historicalQuarter == null) {
            return false;
        } else {
            return historicalQuarter;
        }
    }

    /**
     * Sets the value of the historicalQuarter property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalQuarter(java.lang.Boolean value) {
        this.historicalQuarter = value;
    }

    /**
     * Gets the value of the historicalYear property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalYear() {
        if (historicalYear == null) {
            return false;
        } else {
            return historicalYear;
        }
    }

    /**
     * Sets the value of the historicalYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalYear(java.lang.Boolean value) {
        this.historicalYear = value;
    }

    /**
     * Gets the value of the historicalOther property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isHistoricalOther() {
        if (historicalOther == null) {
            return false;
        } else {
            return historicalOther;
        }
    }

    /**
     * Sets the value of the historicalOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setHistoricalOther(java.lang.Boolean value) {
        this.historicalOther = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Field {

        @XmlAttribute(name = "name", required = true)
        protected java.lang.String name;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String }
         *     
         */
        public java.lang.String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String }
         *     
         */
        public void setName(java.lang.String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="nodeId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="sourceId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="cacheType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Node {

        @XmlAttribute(name = "nodeId", required = true)
        protected java.lang.String nodeId;
        @XmlAttribute(name = "sourceId")
        protected java.lang.String sourceId;
        @XmlAttribute(name = "cacheType")
        protected java.lang.String cacheType;

        /**
         * Gets the value of the nodeId property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String }
         *     
         */
        public java.lang.String getNodeId() {
            return nodeId;
        }

        /**
         * Sets the value of the nodeId property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String }
         *     
         */
        public void setNodeId(java.lang.String value) {
            this.nodeId = value;
        }

        /**
         * Gets the value of the sourceId property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String }
         *     
         */
        public java.lang.String getSourceId() {
            return sourceId;
        }

        /**
         * Sets the value of the sourceId property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String }
         *     
         */
        public void setSourceId(java.lang.String value) {
            this.sourceId = value;
        }

        /**
         * Gets the value of the cacheType property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String }
         *     
         */
        public java.lang.String getCacheType() {
            return cacheType;
        }

        /**
         * Sets the value of the cacheType property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String }
         *     
         */
        public void setCacheType(java.lang.String value) {
            this.cacheType = value;
        }

    }

}
